{
 "title": "New Delhi COVID19 Dashboard Copy",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Positive Cases in last 24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  positive\nfrom data\norder by year desc,month  desc,day  desc \nLIMIT 1"
    }
   ]
  },
  {
   "title": "Recoveries in last 24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  recovered\nfrom data\norder by year desc,month  desc,day  desc \nLIMIT 1"
    }
   ]
  },
  {
   "title": "Deaths in last 24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  deaths\nfrom data\norder by year desc,month  desc,day  desc \nLIMIT 1"
    }
   ]
  },
  {
   "title": "Vaccinations in last 24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  vaccinated\nfrom data\norder by year desc,month  desc,day  desc \nLIMIT 1"
    }
   ]
  },
  {
   "title": "Active Cases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  active_cases\nfrom data\norder by year desc,month  desc,day  desc \nLIMIT 1"
    }
   ]
  },
  {
   "title": "Daily Positive Cases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\", \n\tpositive AS \"Positive Cases\"\nFROM data\norder by time"
    }
   ]
  },
  {
   "title": "Pincode Wise Centers Today",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  CURRENT_TIMESTAMP AS \"time\",\n  PINCODE::varchar AS \"metric\",\n  COUNT(*) AS \"value\"\nfrom centers\nwhere\n  (year || ' ' || month || ' ' || day)::DATE = CURRENT_DATE\ngroup by PINCODE"
    }
   ]
  },
  {
   "title": "Daily Vaccinations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\", \n\tvaccinated AS \"Total Vaccinated\"\nFROM data\norder by time"
    }
   ]
  },
  {
   "title": "Daily Tests Conducted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\", \n\ttests AS \"Tests Conducted\"\nFROM data\norder by time"
    }
   ]
  },
  {
   "title": "Daily Deaths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\", \n\tdeaths AS \"Deaths\"\nFROM data\norder by time"
    }
   ]
  },
  {
   "title": "First vs Second Dose",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\", \n\tfirst_dose AS \"First Dose\"\nFROM data\norder by time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\", \n\tsecond_dose AS \"Second Dose\"\nFROM data\norder by time"
    }
   ]
  },
  {
   "title": "Daily Recoveries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\", \n\trecovered AS \"Recoveries\"\nFROM data\norder by time"
    }
   ]
  },
  {
   "title": "Number of Vaccination Centers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\", \n\tCOUNt(time)\nFROM centers\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Daily Active Cases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\", \n\tactive_cases AS \"Active Cases\"\nFROM data"
    }
   ]
  },
  {
   "title": "District Wise Vaccination Centers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"Central Delhi\"\nFROM centers\nWHERE district_name = 'Central Delhi'\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"New Delhi\"\nFROM centers\nWHERE district_name = 'New Delhi'\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"West Delhi\"\nFROM centers\nWHERE district_name = 'West Delhi'\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"North Delhi\"\nFROM centers\nWHERE district_name = 'North Delhi'\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"South Delhi\"\nFROM centers\nWHERE district_name = 'South Delhi'\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"South East Delhi\"\nFROM centers\nWHERE district_name = 'South East Delhi'\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"East Delhi\"\nFROM centers\nWHERE district_name = 'East Delhi'\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"\tShahdara\"\nFROM centers\nWHERE district_name = '\tShahdara'\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"North West Delhi\"\nFROM centers\nWHERE district_name = 'North West Delhi'\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"South West Delhi\"\nFROM centers\nWHERE district_name = 'South West Delhi'\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Containment Zones",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\", \n\tcont_zones AS \"Containment Zones\"\nFROM data\norder by time"
    }
   ]
  },
  {
   "title": "Vaccine Wise Centers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n  COUNT(*) AS \"COVAXIN\"\nFROM centers\nWHERE vaccine = 'COVAXIN'\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n  COUNT(*) AS \"COVISHIELD\"\nFROM centers\nWHERE vaccine = 'COVISHIELD'\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Age Wise Centers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n\tCOUNT(*) AS \"18+\"\nFROM centers\nWHERE min_age_limit = 18\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n\tCOUNT(*) AS \"45+\"\nFROM centers\nWHERE min_age_limit = 45\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Fee Wise Center",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"FREE\"\nFROM centers\nWHERE fee = 0\nGROUP BY time"
    },
    {
     "rawSql": "SELECT \n\t(year || ' ' || month || ' ' || day)::DATE AS \"time\",\n    COUNT(*) AS \"PAID\"\nFROM centers\nWHERE fee > 0\nGROUP BY time"
    }
   ]
  }
 ]
}